CREATE TABLE users (
    id VARCHAR(26) NOT NULL UNIQUE PRIMARY KEY,
    username VARCHAR(125) NOT NULL UNIQUE,
    email VARCHAR(125) NOT NULL UNIQUE,
    password VARCHAR(125) NOT NULL,
    token_version VARCHAR(26) NOT NULL DEFAULT '',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;